// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	User
	Msg
	DstUser
	Action
	Frame
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserName string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	UserPwd  string `protobuf:"bytes,2,opt,name=userPwd" json:"userPwd,omitempty"`
	UserID   int32  `protobuf:"varint,3,opt,name=userID" json:"userID,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetUserPwd() string {
	if m != nil {
		return m.UserPwd
	}
	return ""
}

func (m *User) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type Msg struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Msg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DstUser struct {
	Dst []*User `protobuf:"bytes,1,rep,name=dst" json:"dst,omitempty"`
}

func (m *DstUser) Reset()                    { *m = DstUser{} }
func (m *DstUser) String() string            { return proto.CompactTextString(m) }
func (*DstUser) ProtoMessage()               {}
func (*DstUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DstUser) GetDst() []*User {
	if m != nil {
		return m.Dst
	}
	return nil
}

type Action struct {
	RslCode    int32 `protobuf:"varint,1,opt,name=rslCode" json:"rslCode,omitempty"`
	ActionType int32 `protobuf:"varint,2,opt,name=actionType" json:"actionType,omitempty"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Action) GetRslCode() int32 {
	if m != nil {
		return m.RslCode
	}
	return 0
}

func (m *Action) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

// 登录，注册，添加好友，删除好友，发送消息
type Frame struct {
	ProtoSign  int32    `protobuf:"varint,1,opt,name=protoSign" json:"protoSign,omitempty"`
	MsgLength  int64    `protobuf:"varint,2,opt,name=msgLength" json:"msgLength,omitempty"`
	MsgType    int32    `protobuf:"varint,3,opt,name=msgType" json:"msgType,omitempty"`
	SenderTime int64    `protobuf:"varint,4,opt,name=senderTime" json:"senderTime,omitempty"`
	Src        *User    `protobuf:"bytes,5,opt,name=src" json:"src,omitempty"`
	Dst        *DstUser `protobuf:"bytes,6,opt,name=dst" json:"dst,omitempty"`
	Msg        *Msg     `protobuf:"bytes,7,opt,name=msg" json:"msg,omitempty"`
	FbAction   *Action  `protobuf:"bytes,8,opt,name=fbAction" json:"fbAction,omitempty"`
}

func (m *Frame) Reset()                    { *m = Frame{} }
func (m *Frame) String() string            { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()               {}
func (*Frame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Frame) GetProtoSign() int32 {
	if m != nil {
		return m.ProtoSign
	}
	return 0
}

func (m *Frame) GetMsgLength() int64 {
	if m != nil {
		return m.MsgLength
	}
	return 0
}

func (m *Frame) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Frame) GetSenderTime() int64 {
	if m != nil {
		return m.SenderTime
	}
	return 0
}

func (m *Frame) GetSrc() *User {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *Frame) GetDst() *DstUser {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *Frame) GetMsg() *Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Frame) GetFbAction() *Action {
	if m != nil {
		return m.FbAction
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "protocol.User")
	proto.RegisterType((*Msg)(nil), "protocol.Msg")
	proto.RegisterType((*DstUser)(nil), "protocol.DstUser")
	proto.RegisterType((*Action)(nil), "protocol.Action")
	proto.RegisterType((*Frame)(nil), "protocol.Frame")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0xa6, 0xcb, 0xda, 0x75, 0x47, 0x1c, 0x33, 0x17, 0x1a, 0x44, 0xb4, 0xd4, 0x9b, 0x82, 0xb2,
	0x0b, 0x7d, 0x02, 0x75, 0x08, 0x82, 0x13, 0x89, 0xf5, 0x01, 0xb6, 0x36, 0xc6, 0xc2, 0xda, 0x8e,
	0x9c, 0x8a, 0xf8, 0x1c, 0xbe, 0xb0, 0xe4, 0xa4, 0x3f, 0xbb, 0xf0, 0xee, 0x7c, 0x3f, 0xc9, 0x77,
	0xce, 0x07, 0xb3, 0x9d, 0xa9, 0x9b, 0x3a, 0xab, 0xb7, 0x0b, 0x1a, 0x78, 0xd8, 0xe1, 0x38, 0x85,
	0xf1, 0x3b, 0x2a, 0xc3, 0x4f, 0x21, 0xfc, 0x42, 0x65, 0x5e, 0xd6, 0xa5, 0x12, 0x5e, 0xe4, 0x25,
	0x53, 0xd9, 0x63, 0x2e, 0x60, 0x62, 0xe7, 0xd7, 0xef, 0x5c, 0x8c, 0x48, 0xea, 0x20, 0x3f, 0x86,
	0xc0, 0x8e, 0x4f, 0x4b, 0xc1, 0x22, 0x2f, 0xf1, 0x65, 0x8b, 0xe2, 0x13, 0x60, 0x2b, 0xd4, 0x7c,
	0x0e, 0xac, 0x44, 0xdd, 0xfe, 0x67, 0xc7, 0xf8, 0x0a, 0x26, 0x4b, 0x6c, 0x28, 0x31, 0x02, 0x96,
	0x63, 0x23, 0xbc, 0x88, 0x25, 0x07, 0x37, 0xb3, 0x45, 0xbf, 0xa1, 0x15, 0xa5, 0x95, 0xe2, 0x7b,
	0x08, 0xee, 0xb2, 0xa6, 0xa8, 0x2b, 0xbb, 0x81, 0xc1, 0xed, 0x43, 0x9d, 0xbb, 0xe5, 0x7c, 0xd9,
	0x41, 0x7e, 0x0e, 0xb0, 0x26, 0x4f, 0xfa, 0xb3, 0x53, 0xb4, 0x9e, 0x2f, 0xf7, 0x98, 0xf8, 0x77,
	0x04, 0xfe, 0xa3, 0xb1, 0x57, 0x9c, 0xc1, 0x94, 0x32, 0xde, 0x0a, 0x5d, 0xb5, 0xbf, 0x0c, 0x84,
	0x55, 0x4b, 0xd4, 0xcf, 0xaa, 0xd2, 0xcd, 0x27, 0x7d, 0xc3, 0xe4, 0x40, 0xd8, 0xfc, 0x12, 0x35,
	0x45, 0xb8, 0x43, 0x3b, 0x68, 0xf3, 0x51, 0x55, 0xb9, 0x32, 0x69, 0x51, 0x2a, 0x31, 0xa6, 0x87,
	0x7b, 0x8c, 0xbd, 0x12, 0x4d, 0x26, 0xfc, 0xc8, 0xfb, 0xef, 0x4a, 0x34, 0x19, 0xbf, 0x74, 0x3d,
	0x04, 0xe4, 0x38, 0x1a, 0x1c, 0x6d, 0x4f, 0x54, 0x05, 0xbf, 0x70, 0x4d, 0x4e, 0xc8, 0x74, 0x38,
	0x98, 0x56, 0xa8, 0xa9, 0x58, 0x7e, 0x0d, 0xe1, 0xc7, 0xc6, 0xb5, 0x25, 0x42, 0x72, 0xcd, 0x07,
	0x97, 0xe3, 0x65, 0xef, 0xd8, 0x04, 0x24, 0xdd, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xad, 0xf2,
	0x50, 0x8c, 0x18, 0x02, 0x00, 0x00,
}
